[project]
name = "cdi-di"
version = "0.0.1-b5"
description = "Python dependency injection made easy"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "daniel sonbolian", email = "dsal3389@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "typing-extensions>=4.15.0",
]

[project.urls]
Repository = "https://github.com/dsal3389/cdi"

[tool.hatch.build.targets.wheel]
packages = ["src/cdi"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
    "pytest>=8.4.2",
]
